export interface Certification {
  id: number;
  title: string;
  issuer: string; // AWS, Alura, Udemy, NTT Data, etc.
  imageUrl: string; // Preview image ou ícone
  credentialUrl: string; // URL do certificado online ou caminho do PDF
  issuedDate: Date;
  expiryDate?: Date; // Opcional - apenas para certificações que expiram
  type: 'aws' | 'course'; // Distingue certificações AWS de cursos
  technologies?: string[]; // Para filtros
  featured?: boolean; // Para destacar certificações importantes
  description?: string;
  pdfPath?: string; // Caminho do PDF local (para certificados em PDF)
  isPdf?: boolean; // Indica se é um certificado em PDF
  hours?: number; // Carga horária do curso
  instructor?: string; // Instrutor do curso
  autoGenerated?: boolean; // Indica se foi gerado automaticamente
}

export interface CertificationFilter {
  name: string;
  key: string;
  icon: string;
}
